# roles/common/tasks/main.yml: master playbook for the common role
- name: create /etc/resolv.conf to configure DNS resolution
  hosts: all
  template: src=roles/common/templates/resolv.conf.j2 dest=/etc/resolv.conf